#!/usr/bin/env python3
"""
set_build_date.py — PlatformIO pre-build script (ALL environments)

[REL-03/REL-04, v1.9.3] Deterministic build identity (reproducible builds).

Problem being fixed
-------------------
Before v1.9.3, Config.h compiled FIRMWARE_BUILD_DATE from `__DATE__ " " __TIME__`
(the wall-clock of the machine running the compiler). Two builds from the SAME
source commit therefore produced byte-different binaries and different
SHA-256s, which:
  - broke REL-04 (build 2x from same source must be byte-identical),
  - broke REL-03 (the hardware-tested binary could never be proven equal to
    the released binary, because every build had a fresh timestamp).

How it works
------------
This script resolves SOURCE_DATE_EPOCH (seconds, UTC) in priority order:
  1. The SOURCE_DATE_EPOCH environment variable — the reproducible-builds.org
     convention; lets CI or a wrapper pin the epoch explicitly.
  2. The timestamp of the HEAD git commit (`git log -1 --format=%ct`).
     Same source commit -> same build date -> byte-identical binary.
  3. 0 (Unix epoch) when git is unavailable (e.g. a source tarball).

It then writes `.pio/generated/plts_build_date.h`:
    #define PLTS_BUILD_DATE_STR "<ISO-8601 UTC>"
and appends that directory to the include path. Config.h picks the macro up
via `__has_include("plts_build_date.h")`; scriptless builds (Arduino IDE)
fall back to a constant epoch string — still deterministic.

The `.pio/` tree is wiped by clean builds, but this pre script runs on every
`pio run`, so the header is regenerated each time — deterministically from
the same SOURCE_DATE_EPOCH, never from the wall clock.

Semantic note
-------------
`buildDate` (exposed via /api/version and shown in the PWA) now reports the
SOURCE commit date rather than the compile wall-clock. For provenance this is
strictly better: the field now ties the running binary to the exact source
commit it was built from. release.json/provenance.json continue to record the
actual buildTimestamp of the CI run as metadata (JSON files, not embedded in
the binary) — the two are deliberately different fields.
"""
import os
import subprocess
import sys
from datetime import datetime, timezone

Import("env")  # noqa: F821  (PlatformIO injects this)

build_env = env  # noqa: F821


def _resolve_source_date_epoch():
    """Return (epoch_seconds, human_readable_source) deterministically."""
    # 1. SOURCE_DATE_EPOCH env var (reproducible-builds.org convention)
    env_val = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    if env_val.isdigit():
        return int(env_val), "SOURCE_DATE_EPOCH env var"

    # 2. git HEAD commit timestamp — same commit always yields the same value
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ct"],
            capture_output=True, text=True, timeout=10, check=True,
        ).stdout.strip()
        if out.isdigit():
            return int(out), "git HEAD commit timestamp"
    except Exception:
        pass

    # 3. Epoch fallback (deterministic constant — never a wall clock)
    return 0, "epoch fallback (git unavailable)"


epoch, source = _resolve_source_date_epoch()
iso = datetime.fromtimestamp(epoch, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# os.getcwd() is the PlatformIO project dir (firmware/) — same convention as
# inject_production_flags.py (__file__ may be unavailable in SCons context).
generated_dir = os.path.join(os.getcwd(), ".pio", "generated")
os.makedirs(generated_dir, exist_ok=True)
header_path = os.path.join(generated_dir, "plts_build_date.h")
with open(header_path, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by firmware/scripts/set_build_date.py — DO NOT EDIT\n")
    f.write("// [REL-03/REL-04 v1.9.3] Deterministic build identity. Never a wall clock.\n")
    f.write(f"// Resolved from: {source}\n")
    f.write("#pragma once\n")
    f.write(f'#define PLTS_BUILD_DATE_STR "{iso}"\n')

build_env.Append(CPPPATH=[generated_dir])

print(f"[set_build_date] PLTS_BUILD_DATE_STR = {iso} (source: {source})")
